config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:dashboard, :update] do
    member do
      get 'dashboard', to: "users#dashboard"
      get 'plants', to: "users#plants"
    end
  end

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :plants, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [ :create ]
  end
  resources :bookings, only: [] do
      resources :reviews, only: [ :new, :create ]
  end
  patch 'bookings/:booking_id/accept', to: "bookings#accept", as: :accept_booking
  patch 'bookings/:booking_id/decline', to: "bookings#decline", as: :decline_booking

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  STATUS = ["accepted", "declined", "pending"]
  belongs_to :plant
  belongs_to :user
  has_many :reviews, dependent: :destroy
  validates :status, inclusion: { in: STATUS }

  validate :end_date_after_start_date?

  def end_date_after_start_date?
    if ends_at < starts_at
      errors.add :ends_at, "must be after start date"
    end
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  CATEGORIES = ["Green Plant", "Blooming Plant", "Decorative Plant", "Large Plant", "Bonsai", "Cactus", "Artificial Plant", "Shrub", "Bamboo", "Fruit Tree", "Conifer"].sort
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true
  validates :price_per_day, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES, case_sensitive: false }
  validates :photo, presence: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  include PgSearch
  pg_search_scope :search_by_name_and_category,
    against: [ :name, :category, :instruction, :address ],
    associated_against: {
      user: [ :firstname, :lastname ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, presence: true
  validates :user, uniqueness: { scope: :booking, message: "you can only leave one review per booking" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :photo, PhotoUploader
  has_many :plants, dependent: :destroy
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def set_disabled_dates
    @disabled = []
    @plant.bookings.each do |booking|
      start = booking.starts_at - 1.day
      @disabled << { from: start, to: booking.ends_at}
    end
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @plant = Plant.find(params[:plant_id])
    @booking = Booking.new(booking_params)
    start_date = @booking.starts_at.to_i
    end_date = @booking.ends_at.to_i
    @booking.total_price = (end_date - start_date) / 86400 * @plant.price_per_day
    @booking.user = current_user
    @booking.plant = @plant
    @booking.status = "pending"
    authorize @booking
    if @booking.save
      redirect_to dashboard_user_path(current_user)
    else
      set_disabled_dates # method defined in ApplicationController
      render 'plants/show'
    end
  end

  def accept
    @booking = Booking.find(params[:booking_id])
    @booking.status = "accepted"
    authorize @booking
    if @booking.save
      redirect_to dashboard_user_path(current_user)
    else
      render 'plants/show'
    end
  end

  def decline
    @booking = Booking.find(params[:booking_id])
    @booking.status = "declined"
    authorize @booking
    if @booking.save
      redirect_to dashboard_user_path(current_user)
    else
      render 'plants/show'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]
  def home
  end

  def about
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
before_action :find_plant, only: [:show, :edit, :update, :destroy]
skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @plants = Plant.where.not(latitude: nil, longitude: nil)
    @markers = @plants.map do |plant|
      {
        lat: plant.latitude,
        lng: plant.longitude,
        icon: "http://res.cloudinary.com/djlkudqpv/image/upload/c_scale,h_30,q_100,r_0,w_30/v1512062487/logo_gcdlo3.png",
        infoWindow: { content: render_to_string(partial: "/plants/map_box", locals: { plant: plant })},

        }
    end

    if params[:query].present?
      @plants = Plant.search_by_name_and_category(params[:query])
    elsif params[:category].present?
      @plants = Plant.search_by_name_and_category(params[:category])
    else
      @plants = Plant.all
    end
  end

  def show
    @booking = Booking.new
    authorize @plant
    set_disabled_dates # method defined in ApplicationController
    @marker = [{ lat: @plant.latitude, lng: @plant.longitude }]
  end

  def new
    @plant = Plant.new
    authorize @plant
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user = current_user
    authorize @plant
    if @plant.save
      redirect_to plant_path(@plant)
    else
      render :new
    end
  end

  def edit
    authorize @plant
  end

  def update
    authorize @plant
    if @plant.save
      redirect_to plant_path(@plant)
    else
      render :edit
    end
  end

  def destroy
    authorize @plant
    @user = @plant.user
    @plant.destroy
    redirect_to plants_user_path(@user)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :instruction, :price_per_day, :category, :address, :photo)
  end

  def find_plant
    @plant = Plant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    authorize @review
    @review.user = current_user
    if @review.save
      redirect_to dashboard_user_path(current_user)
    else
      redirect_to dashboard_user_path(current_user)
    end
  end

  private
  def review_params
    params.require(:review).permit(:content, :rating)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:plants, :dashboard, :update]

  def plants
    authorize @user
    @plants = Plant.where(user: params[:id])
  end

  def dashboard
    @plants = @user.plants
    @bookings = @user.bookings
    authorize @user
  end

  def update
    @user.update(user_params)
    authorize @user
    redirect_to dashboard_user_path(@user)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

  def user_params
    params.require(:user).permit(:name, :plant_id, :username, :firstname, :lastname, :photo, :photo_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Plantor</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag 'favicon.ico'%>

  </head>
  <body>
    <%= render "shared/navbar_home" %>
    <%= render 'shared/alert' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div id="about">
  <div class="container">
    <div class="about-content">
      <h1>The Plantor Team: </h1>
      <ul class="list-inline">
          <li>
            <% link_to "https://kitt.lewagon.com/alumni/juliesimon", target: "_blank" %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/juliesimon", class: "img-about" %>
            <h2>Julie Simon</h2>
          </li>
          <li>
            <% link_to "https://kitt.lewagon.com/alumni/guillaumeh95", target: "_blank" %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/guillaumeh95", class: "img-about" %>
            <h2>Guillaume Hercot</h2>
          </li>
          <li>
            <% link_to "https://kitt.lewagon.com/alumni/mathildanancia", target: "_blank" %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/mathildanancia", class: "img-about" %>
            <h2>Mathilde Ganancia</h2>
          </li>
          <li>
            <% link_to "https://kitt.lewagon.com/alumni/alexialet", target: "_blank" %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/alexialet", class: "img-about" %>
            <h2>Alexia Le Tarnec</h2>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render "shared/banner" %>

app/views/plants/_form.html.erb
<%= simple_form_for @plant do |f| %>
  <%= f.input :name, label: 'Name', placeholder: 'Cute, easy-going cactus'%>
  <%= f.input :instruction, label: 'Instruction', placeholder: 'This cactus is easy to take-care of. It needs to stay away from direct light but still be in a sunny room. Almost never water it !' %>
  <%= f.input :price_per_day, label: 'Price per day (€)', placeholder: '2' %>
  <%= f.input :address, label: 'Location of the plant', placeholder: '23 rue du Terreau, 93260 Les Lilas'  %>
  <%= f.input :category, collection: Plant::CATEGORIES, prompt: "Select a category" %>
  <%= f.input :photo, label: 'Add a Photo' %>
  <%= f.input :photo_cache, as: :hidden %>
  <% if @plant.id.present? %>
    <%= f.submit "Edit your plant", id: "#btn-no-padding", class: "btn-secondary form-button" %>
  <% else %>
    <%= f.submit "Add your plant", id: "#btn-no-padding", class: "btn-secondary form-button" %>
  <% end %>
<% end %>

app/views/plants/_map_box.html.erb
<div class="addressbox">
  <div> <%= cl_image_tag plant.photo, class: "img-circle-map", crop: :fill %></div>
  <h3> <%= plant.name %></h3>
  <p> Located <%= plant.address %></p>
  <%= link_to plant_path(plant) do %><i id="arrow" class="fa fa-long-arrow-right"></i><% end %>
</div>

app/views/plants/edit.html.erb
<h1><%= "Edit #{@plant.name}" %></h1>

<%= render 'form' %>

app/views/plants/index.html.erb
<div class="content">
  <div class="main-content-index">
    <div class="search-index">
    <div class="search-bar">
      <%= form_tag plants_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query] || params[:category],
        class: "form-control",
        placeholder: "Find a plant"
        %>
      <% end %>
    </div>
    <div class="plant-categories">
      <div class="dropdown">
        <div class="btn-category" data-toggle="dropdown"> Categories </div>
        <div class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% Plant::CATEGORIES.each do |category| %>
          <li><%= link_to category, plants_path(category: category) %></li>
          <% end %>
        </div>
      </div>
  </div>
  </div>

  <div class="card-container">
    <% @plants.each do |plant| %>
        <%= render "shared/card", plant: plant %>
    <% end %>
    </div>
  </div>
  <div id="map" data-markers="<%= @markers.to_json %>"></div>
</div>

app/views/plants/new.html.erb
<div class= "container-form">
  <div class="form-new">
    <h1> <%= image_tag('logo.png', class:'icon') %> Add a new plant</h1>
    <%= render 'form' %>

  </div>
</div>

app/views/plants/show.html.erb
<div class="body">
  <div class="banner-plant" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%),url('<%= cl_image_path @plant.photo %>')">
    <div class="banner">
    <h2><%= @plant.name %></h2>
    </div>
  </div>
        <%= link_to plants_path, class: "btn btn-back" do %>
          <i class="fa fa-long-arrow-left"></i> Back to list
        <% end %>
  <div class="container-plant">
    <div class="plant-information">
      <div id="plant-description">
        <h4>About this plant</h4>
        <h6><i class="fa fa-leaf" aria-hidden="true"></i> Category:</h6>
        <p><%= @plant.category %></p>
        <h6><i class="fa fa-info" aria-hidden="true"></i> Instructions: </h6>
          <p><%= @plant.instruction %></p>
        <h6><i class="fa fa-location-arrow" aria-hidden="true"></i> Address:</h6>
          <p><%= @plant.address %></p>
        <h6><i class="fa fa-eur" aria-hidden="true"></i> Price/day: </h6>
        <p class="price-per-day"><%= @plant.price_per_day %></p>
        <h6><i class="fa fa-user" aria-hidden="true"></i> Owner: </h6>
        <p><%= @plant.user.firstname %> <%= @plant.user.lastname %>
           <%= mail_to @plant.user.email, '<i class="fa fa-envelope" aria-hidden="true"></i>'.html_safe %></p>
      </div>
      <div id="plant-reviews">
          <% if @plant.reviews.any? %>
            <h6><i class="fa fa-comments-o" aria-hidden="true"></i> Reviews about the plant: </h6>
              <div class="review-content"> <% @plant.reviews.each do |review| %>
              <% review.rating.times do %>
                <i class="fa fa-star yellow-star" aria-hidden="true"></i>
              <% end %>
              <% (5 - review.rating).times do %>
                <i class="fa fa-star-o empty-yellow-star" aria-hidden="true"></i>
              <% end %>
             <p><%= review.content %></p>
            <% end %>
            </div>
          <% else %>
          <h6><i class="fa fa-comments-o" aria-hidden="true"></i> No reviews about this plant yet ! </h6>
       <% end %>
       <br>
      </div>
    </div>
      <div id="booking-form" data-dates="<%= @disabled.to_json %>">
      <%= render "shared/form" %>
      </div>
  </div>
    <div class="map">
      <h6><i class="fa fa-map-marker" aria-hidden="true"></i> Location of the plant: <br></h6>
      <div id="map" style="width: 100%; height: 300px;" data-markers="<%= @marker.to_json %>"></div>
    </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [booking, review] do |f| %>
  <%= f.input :content, label: 'Review', placeholder: 'Beautiful plant', style: "text-align: left"%>
  <%= f.input :rating, label: 'Rating', :collection => [0, 1, 2, 3, 4, 5] %>
  <%= f.submit "Submit Review", class: "btn-secondary form-button" %>
<% end %>

app/views/shared/_alert.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%),url('<%= image_path "plant_background.jpg", class: "background-image" %>');">
  <div class="banner-home">
    <h1> Plantor</h1>
    <p>Rent beautiful plants from people around you</p>
      <div class="enter">
           <div class="btn-home">
          <%= link_to "Find a plant", plants_path(@plant), class: "btn-home" %>
        </div>
      </div>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card full-card" style="background-image: linear-gradient(rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.4) 50%), url('<%= cl_image_path plant.photo, crop: :fill %>')">
  <div class="card-info-small card-info">
    <div class="card-description">
      <h3><%= plant.name %></h3>
      <p><%= "#{plant.price_per_day} €/day" %></p>
    </div>
    <div class="card-more-description">
      <div>
        <h6><i class="fa fa-leaf" aria-hidden="true"></i> Category:</h6>
        <p><%= plant.category %></p>
      </div>
      <div>
        <h6><i class="fa fa-star" aria-hidden="true"></i> Rating:</h6>
        <p>
          <% total = 0 %>
          <% nb_reviews = 0 %>
          <% plant.reviews.each do |review| %>
            <% nb_reviews += 1 %>
            <% total += review.rating %>
          <% end %>
          <% if nb_reviews == 0 %>
            No reviews yet
          <% else %>
            <% stars = (total / nb_reviews).round  %>
            <% stars.times do %>
              <i class="fa fa-star yellow-star" aria-hidden="true"></i>
            <% end %>
            <% (5 - stars).times do %>
              <i class="fa fa-star-o empty-yellow-star" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <%= link_to "", plant_path(plant), class: "card-link" %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/juliesimon/plantor"><i class="fa fa-github"></i></a>
    <a href="https://www.facebook.com/lewagonfrance/"><i class="fa fa-facebook"></i></a>
  </div>

  <div class="footer-copyright">
    <%= link_to "About us", about_path %>  ||
    This footer is made with <i class="fa fa-heart"></i> by the Plantor team
  </div>
</div>

app/views/shared/_form.html.erb
<div class="book-form">
  <h4>Book this plant</h4>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <%= simple_form_for [@plant, @booking] do |f| %>
      <%= f.error_notification %>
      <%= f.input :starts_at, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :ends_at, as: :string, required: false, input_html: {class: "datepicker"} %>
      <div class="total-price hidden">
        <div class="total-price-computation"></div>
        <div class="total-price-result"></div>
      </div>
      <%= f.submit "Book it", id: "btn-no-padding", class: "btn-secondary form-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo.png", class: "logo" %>
  </a>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <div class="navbar-wagon-right hidden-xs hidden-sm">
        <% if user_signed_in? %>
          <%= link_to 'My Dashboard', dashboard_user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to 'Add a plant', new_plant_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to 'Find', plants_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
        <% else %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
        <li> <%= link_to 'My Dashboard', dashboard_user_path(current_user) %></li>
        <li> <%= link_to 'Add a plant', new_plant_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to 'Find', plants_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo.png", class: "logo" %>
  </a>
  <div class="navbar-wagon-item">
    <div class="dropdown">
      <div class="navbar-wagon-right hidden-xs hidden-sm">
      <% if user_signed_in? %>
      <%= link_to 'My Dashboard', dashboard_user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to 'Add a plant', new_plant_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to 'Find', plants_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
      <% else %>
      <a href="/users/sign_up" class="navbar-wagon-item navbar-wagon-link">Sign up</a>
      <a href="/users/sign_in" class="navbar-wagon-item navbar-wagon-link">Sign in</a>
      <% end %>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
      <li><%= link_to 'My Dashboard', dashboard_user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %></li>
      <li><%= link_to 'Add a plant', new_plant_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %></li>
      <li><%= link_to 'Find', plants_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %></li>
    <% else %>
        <li><a href="/users/sign_up">Sign up</a></li>
        <li><a href="/users/sign_in">Sign in</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/_form-user.html.erb
<div class= "container-form">
  <%= simple_form_for @user do |f| %>
    <%= f.input :username, label: 'Username', placeholder: 'Username'%>
    <%= f.input :photo, placeholder: "Add a Photo", label: false %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Add to Profile", :class =>"btn-secondary form-button"  %>
  <% end %>
</div>

app/views/users/_headers.html.erb
<li class="booking">
  <div class="booking-user-photo"></div>
  <div class="booking-plant-photo"></div>
  <div class="booking-plant"><strong>Plant</strong></div>
  <div class="booking-user"><strong>Contact</strong></div>
  <div class="booking-dates">
    <div class="booking-start"><strong>From</strong></div>
    <div class="booking-end"><strong>To</strong></div>
  </div>
  <div class="booking-status"><strong>Status</strong></div>
</li>

app/views/users/plants.html.erb
<div class="all-my-plants ">
  <div class="all-my-plants-bis ">
    <%= link_to dashboard_user_path(@user), class: "btn btn-back" do %>
<i class="fa fa-long-arrow-left"></i> Back
<% end %>
    <div class="list-of-plants text-center">
      <h3>All my plants</h3>
    <ul>
      <li class="plant-list">
        <div class="plant-list-plant-photo"></div>
        <div class="plant-list-name"><strong>Title</strong></div>
        <div class="plant-list-small"><strong>Pending<br>Requests</strong></div>
        <div class="plant-list-small"><strong>Accepted<br>Requests</strong></div>
        <div class="plant-list-small"><strong>Average<br>Rating</strong></div>
      </li>
      <% @plants.each do |plant| %>
        <li class="plant-list">
          <div class="plant-list-plant-photo">
            <%= cl_image_tag plant.photo, crop: :fill %>
          </div>
          <div class="plant-list-name">
            <%= link_to plant.name, plant_path(plant) %>
            <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_plant_path(plant) %>
            <%= link_to '<i class="fa fa-times delete-red" aria-hidden="true"></i>'.html_safe, plant_path(plant), method: :delete,
            data: { confirm: "Are you sure you want to delete this plant?" } %>
          </div>
          <div class="plant-list-small">
            <%= link_to plant.bookings.where(status:"pending").length, dashboard_user_path(@user) %>
          </div>
          <div class="plant-list-small">
            <%= link_to plant.bookings.where(status:"accepted").length, dashboard_user_path(@user) %>
          </div>
          <div class="plant-list-small">
            <% total = 0%>
            <% nb_reviews = 0 %>
            <% plant.reviews.each do |review| %>
              <% nb_reviews += 1 %>
              <% total += review.rating %>
            <% end %>
            <% if nb_reviews == 0 %>
              No reviews yet
            <% else %>
              <% stars = (total / nb_reviews).round  %>
              <% stars.times do %>
                <i class="fa fa-star yellow-star" aria-hidden="true"></i>
              <% end %>
              <% (5 - stars).times do %>
                <i class="fa fa-star-o empty-yellow-star" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
    </div>
  </div>
</div>